const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { launch } = require('./vscodeTestLauncher');
const root = path.resolve(__dirname, '..'); const repo = path.resolve(root, '..', '..');
const mode = process.env.STAGE7_SMOKE_MODE || 'smoke'; const temp = fs.mkdtempSync(path.join(repo, 'artifacts', 'ai-worklog-stage7-smoke-')); const report = process.env.STAGE7_SMOKE_REPORT || path.join(repo, 'artifacts', 'test-results', `stage07-${mode}.json`); const fixture = path.join(root, 'test-fixtures', 'event-capture-workspace'); const workspace = path.join(temp, 'workspace'); const data = path.join(temp, 'data'); const userData = path.join(temp, 'user-data'); const extensions = path.join(temp, 'extensions');
fs.cpSync(fixture, workspace, { recursive: true }); fs.mkdirSync(data, { recursive: true }); fs.writeFileSync(path.join(workspace, '.vscode', 'settings.json'), JSON.stringify({ 'aiWorklog.serverPort': 0, 'aiWorklog.dataDir': data }));
const received = []; const fake = http.createServer((req, res) => { let body=''; req.on('data', c => body += c); req.on('end', () => { received.push({ auth: req.headers.authorization, body }); res.setHeader('content-type','application/json'); res.end(JSON.stringify({ choices:[{ message:{ content:'OK' } }] })); }); });
async function one(phase) { const port = fake.address().port; const result = await launch({ extensionDevelopmentPath: root, extensionTestsPath: path.join(root,'test','suite'), workspace, userData, extensions, logs:path.join(temp,`logs-${phase}`), env:{ STAGE7_SMOKE_E2E:'1', STAGE7_SMOKE_PHASE:phase, STAGE7_SMOKE_REPORT:report, STAGE7_PROFILE_ID:'stage7-smoke-profile', STAGE7_FAKE_URL:`http://127.0.0.1:${port}/v1` } }); if (result.code !== 0) throw Error(`Extension Host exited ${result.code}`); }
(async()=>{ try { await new Promise(resolve=>fake.listen(0,'127.0.0.1',resolve)); if(mode === 'persistence') { await one('persistence-host1'); await one('persistence-host2'); } else await one('smoke'); const auth=received[0]?.auth; if(!/^Bearer stage7-[0-9a-f-]+$/i.test(auth||'') || received.some(item=>item.auth!==auth || item.body.includes('taskId'))) throw Error('fake provider contract failed'); } catch(error) { if(!fs.existsSync(report)) { fs.mkdirSync(path.dirname(report),{recursive:true}); fs.writeFileSync(report,JSON.stringify({status:'failed',error:String(error)},null,2)); } console.error(error); process.exitCode=1; } finally { await new Promise(resolve=>fake.close(resolve)); if(process.env.STAGE7_E2E_KEEP_TEMP==='1') console.error(`STAGE7_SMOKE_TEMP=${temp}`); else fs.rmSync(temp,{recursive:true,force:true}); } })();
