const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { launch } = require('./vscodeTestLauncher');

const root = path.resolve(__dirname, '..');
const repo = path.resolve(root, '..', '..');
const fixture = path.join(root, 'test-fixtures', 'event-capture-workspace');
const temp = fs.mkdtempSync(path.join(repo, 'artifacts', 'ai-worklog-stage7-e2e-'));
const workspace = path.join(temp, 'workspace'); const data = path.join(temp, 'data');
const report = process.env.STAGE7_E2E_REPORT || path.join(repo, 'artifacts', 'test-results', 'stage07-extension-host-ai-provider.json');
fs.cpSync(fixture, workspace, { recursive: true }); fs.mkdirSync(data, { recursive: true }); fs.mkdirSync(path.join(workspace, '.vscode'), { recursive: true });
fs.writeFileSync(path.join(workspace, '.vscode', 'settings.json'), JSON.stringify({ 'aiWorklog.serverPort': 0, 'aiWorklog.dataDir': data }));
const received = []; const fake = http.createServer((req, res) => { let body = ''; req.on('data', chunk => body += chunk); req.on('end', () => { try { const parsed = JSON.parse(body); received.push({ auth: req.headers.authorization, body: parsed }); const status = { 'fail-401': 401, 'fail-403': 403, 'fail-404': 404, 'fail-429': 429, 'fail-500': 500 }[parsed.model]; if (status) { res.statusCode = status; res.end('provider secret body'); return; } if (parsed.model === 'fail-connection-reset') { req.socket.destroy(); return; } if (parsed.model === 'fail-timeout') return; if (parsed.model === 'fail-invalid-json') { res.end('not json'); return; } if (parsed.model === 'fail-missing-fields') { res.setHeader('content-type', 'application/json'); res.end('{}'); return; } if (parsed.model === 'fail-oversized') { res.setHeader('content-type', 'application/json'); res.end(JSON.stringify({ choices: [{ message: { content: 'x'.repeat(66000) } }] })); return; } res.setHeader('content-type', 'application/json'); res.end(JSON.stringify({ choices: [{ message: { content: 'OK' } }] })); } catch { res.statusCode = 400; res.end('bad'); } }); });
(async () => { try { await new Promise(resolve => fake.listen(0, '127.0.0.1', resolve)); const port = fake.address().port; const launched = await launch({ extensionDevelopmentPath: root, extensionTestsPath: path.join(root, 'test', 'suite'), workspace, userData: path.join(temp, 'user-data'), extensions: path.join(temp, 'extensions'), logs: path.join(temp, 'vscode-logs'), env: { STAGE7_E2E: '1', STAGE7_E2E_REPORT: report, STAGE7_FAKE_URL: `http://127.0.0.1:${port}/v1` } }); if (launched.code !== 0) throw Error(`Extension Host exited ${launched.code}`); if (received.length !== 14) throw Error(`expected 14 provider calls, got ${received.length}`); const auth = received[0]?.auth; if (!/^Bearer stage7-[0-9a-f-]+$/i.test(auth || '') || received.some(item => item.auth !== auth || JSON.stringify(item.body).includes('taskId'))) throw Error('fake provider contract failed'); } catch (error) { fs.mkdirSync(path.dirname(report), { recursive:true }); if (!fs.existsSync(report)) fs.writeFileSync(report, JSON.stringify({ status:'failed', error:String(error) },null,2)); console.error(error); process.exitCode=1; } finally { await new Promise(resolve=>fake.close(resolve)); if(process.env.STAGE7_E2E_KEEP_TEMP==='1')console.error(`STAGE7_E2E_TEMP=${temp}`);else fs.rmSync(temp,{recursive:true,force:true}); } })();
