import * as vscode from 'vscode';
import * as crypto from 'crypto';

const state: { task?: any; bug?: any; token: string } = { token: crypto.randomBytes(24).toString('hex') };
function base(context: vscode.ExtensionContext) { return `http://127.0.0.1:${vscode.workspace.getConfiguration('aiWorklog').get('serverPort',8765)}`; }
async function api(context:vscode.ExtensionContext,path:string,init:RequestInit={}) { const headers:any={'content-type':'application/json','authorization':`Bearer ${state.token}`,...(init.headers||{})}; const r=await fetch(base(context)+path,{...init,headers}); if(!r.ok) throw new Error(await r.text()); return r.json(); }
async function start(context:vscode.ExtensionContext) { const name=await vscode.window.showInputBox({prompt:'任务名称'}); if(!name)return; const project=vscode.workspace.name||'未命名项目'; state.task=await api(context,'/tasks',{method:'POST',body:JSON.stringify({name,project})}); await api(context,'/events',{method:'POST',body:JSON.stringify({projectId:state.task.project_id,taskId:state.task.id,type:'task_started',timestamp:new Date().toISOString(),payload:{name}})}); vscode.window.showInformationMessage('已开始记录：'+name); }
async function end(context:vscode.ExtensionContext) { if(!state.task)return vscode.window.showWarningMessage('当前没有活动任务'); await api(context,`/tasks/${state.task.id}/end`,{method:'POST'}); const s=await api(context,`/tasks/${state.task.id}/summaries/generate`,{method:'POST'}); vscode.window.showInformationMessage('已生成总结草稿'); state.task=await api(context,`/tasks/${state.task.id}`); await review(context,s); }
async function review(context:vscode.ExtensionContext,s:any) { const panel=vscode.window.createWebviewPanel('aiWorklogReview','AI Worklog Review',vscode.ViewColumn.One,{enableScripts:true}); panel.webview.html=`<!doctype html><html><body><h1>任务审核</h1><textarea id="content" style="width:100%;height:70vh">${escapeHtml(JSON.stringify(s.content,null,2))}</textarea><button onclick="confirmDraft()">确认并写入知识库</button><script>const vscode=acquireVsCodeApi();function confirmDraft(){vscode.postMessage({type:'confirm',content:JSON.parse(document.getElementById('content').value)})}</script></body></html>`; panel.webview.onDidReceiveMessage(async m=>{if(m.type==='confirm'){await api(context,`/summaries/${s.id}`,{method:'PUT',body:JSON.stringify({content:m.content})});await api(context,`/summaries/${s.id}/confirm`,{method:'POST'});vscode.window.showInformationMessage('已确认并写入 Markdown 知识库');panel.dispose();}}); }
function escapeHtml(s:string){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
class Provider implements vscode.WebviewViewProvider { resolveWebviewView(view:vscode.WebviewView){view.webview.options={enableScripts:true};view.webview.html=`<h3>AI Worklog</h3><p>${state.task?'记录中：'+state.task.name:'暂无活动任务'}</p><button onclick="vscode.postMessage({t:'start'})">开始任务</button><button onclick="vscode.postMessage({t:'end'})">结束任务</button>`;view.webview.onDidReceiveMessage(m=>m.t==='start'?start(this.context):end(this.context));} constructor(private context:vscode.ExtensionContext){} }
export function activate(context:vscode.ExtensionContext){
  const commands:{id:string;fn:()=>any}[]=[{id:'aiWorklog.startTask',fn:()=>start(context)},{id:'aiWorklog.endTask',fn:()=>end(context)},{id:'aiWorklog.createBug',fn:async()=>{if(state.task){const title=await vscode.window.showInputBox({prompt:'Bug 标题'});if(title)state.bug=await api(context,`/tasks/${state.task.id}/bugs`,{method:'POST',body:JSON.stringify({title})});}}},{id:'aiWorklog.resolveBug',fn:async()=>{if(state.bug)await api(context,`/bugs/${state.bug.id}/resolve`,{method:'POST'});}}]; commands.forEach(c=>context.subscriptions.push(vscode.commands.registerCommand(c.id,c.fn))); context.subscriptions.push(vscode.window.registerWebviewViewProvider('aiWorklog.sidebar',new Provider(context))); const bar=vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left);bar.text='$(pencil) Worklog';bar.command='aiWorklog.startTask';bar.show();context.subscriptions.push(bar);
  vscode.workspace.onDidSaveTextDocument(d=>{if(state.task)api(context,'/events',{method:'POST',body:JSON.stringify({projectId:state.task.project_id,taskId:state.task.id,type:'file_saved',timestamp:new Date().toISOString(),payload:{file:d.uri.fsPath}})}).catch(()=>undefined);});
}
export function deactivate(){}
