import * as crypto from 'node:crypto';
import * as vscode from 'vscode';
import { ApiClient, ApiError, TaskView } from '../../apiClient';
import { AiProfileStore } from '../profileStore';
import { ContextClient } from '../context/client';
import { ContextPackage } from '../context/types';
import { GenerationClient } from './client';
import { SummaryDraftPanel } from './draftPanel';
import { GenerationJob, generationStatusLabel } from './types';
import { formToContent } from './formModel';
import { confirmationText, generationConfirmation } from './viewModel';

export interface GenerationCommandDeps { api(): Promise<ApiClient>; profiles: AiProfileStore; onStatus?(job: GenerationJob | undefined): void; log?(message: string): void; }
const shortId = (value: string | undefined) => value ? value.slice(0, 12) : '-';
export function generationErrorMessage(error: unknown): string {
  if (error instanceof ApiError) {
    if (error.status === 404 && !error.errorCode) return 'AI 生成接口在当前后端中不可用，请重新构建后端。';
    return ({ context_not_found: '未找到所选 Ready Context。', context_not_ready: '所选 Context 不是 Ready 状态。', task_not_found: '所选任务不存在。', provider_key_missing: '所选 AI Profile 未配置 API Key。', provider_not_configured: '当前后端未配置 AI 总结生成能力。' } as Record<string, string>)[error.errorCode || ''] || `AI 总结生成请求失败（HTTP ${error.status}）。`;
  }
  return error instanceof Error ? error.message : String(error);
}
const taskPicker = async (api: ApiClient): Promise<TaskView | undefined> => vscode.window.showQuickPick((await api.listTasks('completed')).map(task => ({ label: task.name, description: task.ended_at ? new Date(task.ended_at).toLocaleString() : '', task })), { title: 'Select completed task' }).then(choice => choice?.task);
const readyContext = async (api: ApiClient, task: TaskView): Promise<ContextPackage | undefined> => { const options = (await new ContextClient(api).list(task.id)).filter(item => item.status === 'ready').map(item => ({ label: `${item.content_hash.slice(0, 12)}…`, description: `${item.estimated_tokens} input tokens`, item })); if (!options.length) { vscode.window.showWarningMessage('No Ready AI Context Package exists for this task.'); return; } return options.length === 1 ? options[0].item : vscode.window.showQuickPick(options, { title: 'Select Ready Context Package' }).then(choice => choice?.item); };
function confirmation(contextPackage: ContextPackage, task: TaskView, profile: Parameters<typeof generationConfirmation>[2]): Thenable<string | undefined> { return vscode.window.showWarningMessage(confirmationText(generationConfirmation(task.name, contextPackage, profile)), { modal: true }, 'Generate summary draft'); }
export function registerGenerationCommands(context: vscode.ExtensionContext, deps: GenerationCommandDeps): void {
  let panel: SummaryDraftPanel | undefined; let runningJobId: string | undefined;
  let selectedTask: TaskView | undefined; let selectedDraftId: string | undefined; let selectedRevisionId: string | undefined;
  const refreshPanel = async () => { if (!selectedTask || !selectedDraftId || !panel || panel.isDisposed) return; const api = await deps.api(); const client = new GenerationClient(api); const drafts = await client.drafts(selectedTask.id); const draft = drafts.find(item => item.id === selectedDraftId) || drafts[0]; if (!draft) return; selectedDraftId = draft.id; const revisions = await client.revisions(draft.id); const review = await client.reviews(selectedTask.id); const selectedRevision = revisions.find(item => item.id === selectedRevisionId); panel.show({ taskId: selectedTask.id, drafts, draft, revisions, selectedRevision, review }); };
  const openDraft = async (task?: TaskView) => { const api = await deps.api(); const selected = task || await taskPicker(api); if (!selected) return; const drafts = await new GenerationClient(api).drafts(selected.id); if (!drafts.length) { vscode.window.showInformationMessage('No AI summary drafts exist for this task.'); return; } selectedTask = selected; selectedDraftId = drafts[0].id; selectedRevisionId = undefined; if (!panel || panel.isDisposed) { const view = vscode.window.createWebviewPanel('aiWorklog.summaryDraft', 'AI 总结审核', vscode.ViewColumn.Active, { enableScripts: true }); panel = new SummaryDraftPanel(view, { selectDraft: id => { selectedDraftId = id; selectedRevisionId = undefined; void refreshPanel(); }, selectRevision: id => { selectedRevisionId = id === 'original' ? undefined : id; void refreshPanel(); }, save: form => { if (!selectedTask || !selectedDraftId) return; void (async () => { try { const revision = await new GenerationClient(await deps.api()).saveRevision(selectedTask!.id, selectedDraftId!, formToContent(form), crypto.randomUUID()); selectedRevisionId = revision.id; await refreshPanel(); vscode.window.showInformationMessage('已保存为新的 Revision。'); } catch (error) { vscode.window.showErrorMessage(generationErrorMessage(error)); } })(); }, approve: id => { if (!selectedTask || !selectedDraftId) return; void (async () => { try { await new GenerationClient(await deps.api()).approve(selectedTask!.id, selectedDraftId!, id); await refreshPanel(); vscode.window.showInformationMessage('Revision 已批准；任务仍保持 completed。'); } catch (error) { vscode.window.showErrorMessage(generationErrorMessage(error)); } })(); }, reject: (id, reason) => { if (!selectedTask || !selectedDraftId) return; void (async () => { try { await new GenerationClient(await deps.api()).reject(selectedTask!.id, selectedDraftId!, id, reason); await refreshPanel(); vscode.window.showInformationMessage('内容已拒绝，历史记录已保留。'); } catch (error) { vscode.window.showErrorMessage(generationErrorMessage(error)); } })(); }, reload: () => { void refreshPanel(); } }, () => { panel = undefined; }); context.subscriptions.push(panel); } await refreshPanel(); };
  context.subscriptions.push(vscode.commands.registerCommand('aiWorklog.generateAiSummaryDraft', async () => {
    if (runningJobId) { vscode.window.showInformationMessage('An AI summary generation is already running.'); return; }
    const api = await deps.api();
    try {
      const health = await api.health();
      deps.log?.(`[summary-generation] phase=capability method=GET path=/health status=200 features=${(health.features || []).join(',')}`);
      if (!health.features?.includes('ai-summary-generation-v1')) { vscode.window.showErrorMessage('当前后端版本不支持 AI 总结生成，请重新构建后端。'); return; }
    } catch (error) { vscode.window.showErrorMessage(generationErrorMessage(error)); return; }
    const task = await taskPicker(api); if (!task) return;
    const packageToSend = await readyContext(api, task); if (!packageToSend) return;
    const profile = deps.profiles.current(); if (!profile) { vscode.window.showWarningMessage('Configure an AI Provider Profile first.'); return; }
    // SecretStorage is intentionally read only after explicit confirmation.
    if (await confirmation(packageToSend, task, profile) !== 'Generate summary draft') return;
    const apiKey = await deps.profiles.key(profile.id); if (!apiKey) { vscode.window.showWarningMessage('The selected AI Provider Profile has no API key.'); return; }
    const client = new GenerationClient(api); let progress: vscode.Progress<{ message?: string; increment?: number }> | undefined;
    try { await vscode.window.withProgress({ location: vscode.ProgressLocation.Notification, title: 'Generating AI summary draft', cancellable: false }, async report => { progress = report; deps.log?.(`[summary-generation] phase=create method=POST path=/ai/context-packages/${shortId(packageToSend.id)}/summary-generations task=${shortId(task.id)} context=${shortId(packageToSend.id)} profile=${shortId(profile.id)}`); const created = await client.create(packageToSend.id, { profile_id: profile.id, provider: profile.provider, base_url: profile.baseUrl, model: profile.model, thinking_enabled: profile.thinkingEnabled, timeout_seconds: profile.timeoutSeconds, max_output_tokens: profile.maxOutputTokens, api_key: apiKey }, crypto.randomUUID()); runningJobId = created.job_id || created.id; if (!runningJobId) throw new Error('Backend did not return a generation job id'); deps.onStatus?.(created); const result = await client.wait(runningJobId, job => { deps.onStatus?.(job); progress?.report({ message: generationStatusLabel(job.status) }); }); if (result.status !== 'succeeded') throw new Error(result.error_summary || `Generation ${result.status}`); vscode.window.showInformationMessage('AI summary draft generated.'); await openDraft(task); }); } catch (error) { const message = generationErrorMessage(error); const detail = error instanceof ApiError ? ` status=${error.status} code=${error.errorCode || '-'}` : ''; deps.log?.(`[summary-generation] phase=failed${detail} task=${shortId(task.id)} context=${shortId(packageToSend.id)} profile=${shortId(profile.id)}`); vscode.window.showErrorMessage(message); } finally { runningJobId = undefined; }
  }));
  context.subscriptions.push(vscode.commands.registerCommand('aiWorklog.viewAiSummaryDrafts', () => openDraft()));
  const approvedTask = async (): Promise<TaskView | undefined> => taskPicker(await deps.api());
  context.subscriptions.push(vscode.commands.registerCommand('aiWorklog.exportApprovedSummary', async () => { const task = await approvedTask(); if (!task) return; try { await new GenerationClient(await deps.api()).exportSummary(task.id); vscode.window.showInformationMessage('已导出已批准的任务总结。'); } catch (error) { vscode.window.showErrorMessage(generationErrorMessage(error)); } }));
  context.subscriptions.push(vscode.commands.registerCommand('aiWorklog.exportApprovedDailyReport', async () => { const task = await approvedTask(); if (!task) return; try { await new GenerationClient(await deps.api()).exportDaily(task.id); vscode.window.showInformationMessage('已导出已批准的日报。'); } catch (error) { vscode.window.showErrorMessage(generationErrorMessage(error)); } }));
  context.subscriptions.push(vscode.commands.registerCommand('aiWorklog.publishKnowledgeCandidates', async () => { const task = await approvedTask(); if (!task) return; try { const client = new GenerationClient(await deps.api()); const candidates = await client.candidates(task.id); const selected = await vscode.window.showQuickPick(candidates.map(item => ({ label: item.title, description: item.category, detail: item.summary, item })), { title: '选择要发布的知识候选', canPickMany: true }); if (!selected?.length) return; const edited = []; for (const choice of selected) { const title = await vscode.window.showInputBox({ prompt: '发布标题', value: choice.item.title }); if (title === undefined) return; const category = await vscode.window.showInputBox({ prompt: '分类', value: choice.item.category }); if (category === undefined) return; const summary = await vscode.window.showInputBox({ prompt: '知识正文/摘要', value: choice.item.summary }); if (summary === undefined) return; const why = await vscode.window.showInputBox({ prompt: '可复用说明', value: choice.item.why_reusable }); if (why === undefined) return; edited.push({ ...choice.item, title, category, summary, why_reusable: why }); } await client.publishKnowledge(task.id, edited); vscode.window.showInformationMessage(`已发布 ${edited.length} 条知识。`); } catch (error) { vscode.window.showErrorMessage(generationErrorMessage(error)); } }));
  context.subscriptions.push(vscode.commands.registerCommand('aiWorklog.cancelAiSummaryGeneration', async () => { if (!runningJobId) { vscode.window.showInformationMessage('No AI summary generation is running.'); return; } const job = await new GenerationClient(await deps.api()).cancel(runningJobId); deps.onStatus?.(job); vscode.window.showInformationMessage('AI summary generation cancelled.'); }));
}
