import { AiContextPackage, AiSummaryDraft } from '../../apiClient';
import { AiProviderProfile } from '../profileStore';
import { GenerationJob, generationStatusLabel } from './types';

export const draftSectionNames = ['task_summary', 'code_changes', 'commands_and_results', 'bug_solutions', 'unresolved_issues', 'todos', 'daily_report', 'knowledge_candidates'] as const;
export type DraftSectionName = typeof draftSectionNames[number];
export interface GenerationConfirmation { taskName: string; contextId: string; contextHash: string; contextSchema: string; estimatedInputTokens: number; provider: string; profile: string; model: string; thinking: boolean; maxOutputTokens: number; redactionCount: number; truncationCount: number; }
export function generationConfirmation(taskName: string, contextPackage: AiContextPackage, profile: AiProviderProfile): GenerationConfirmation { return { taskName, contextId: contextPackage.id.slice(0, 12), contextHash: contextPackage.content_hash.slice(0, 12), contextSchema: contextPackage.context.schema_version, estimatedInputTokens: contextPackage.estimated_tokens, provider: profile.provider, profile: profile.displayName, model: profile.model, thinking: profile.thinkingEnabled, maxOutputTokens: profile.maxOutputTokens, redactionCount: contextPackage.redaction_count, truncationCount: contextPackage.truncation_count }; }
export function confirmationText(value: GenerationConfirmation): string { return `This will send the selected Ready Context Package to the AI provider.\nTask: ${value.taskName}\nContext: ${value.contextId}…\nHash: ${value.contextHash}…\nSchema: ${value.contextSchema}\nInput tokens: ${value.estimatedInputTokens}\nProvider/Profile: ${value.provider} / ${value.profile}\nModel: ${value.model}\nThinking: ${value.thinking ? 'on' : 'off'}\nMax output tokens: ${value.maxOutputTokens}\nRedactions: ${value.redactionCount}; truncations: ${value.truncationCount}`; }
export function draftSections(draft: AiSummaryDraft): Array<{ name: DraftSectionName; value: unknown }> { const content = draft.content_json || draft.content; const sections = (content?.sections || {}) as Record<DraftSectionName, unknown>; return draftSectionNames.map(name => ({ name, value: sections[name] ?? (name === 'task_summary' || name === 'daily_report' ? {} : []) })); }
export function generationFingerprint(job: GenerationJob | undefined): string { return job ? [job.id || job.job_id || '', job.status, job.provider || '', job.model || '', job.error_code || '', job.error_summary || '', job.attempt_count || 0].join('|') : 'none'; }
export function generationSidebarText(job: GenerationJob | undefined): string { return job ? `AI Summary: ${generationStatusLabel(job.status)}` : 'AI Summary: not generated'; }
