import test from 'node:test';
import assert from 'node:assert/strict';
import { AiProfileStore, defaultsFor, endpointSummary, minimumStructuredOutputTokens, qwenRegionOptions, qwenWorkspaceBaseUrl, secretKey } from './profileStore';

class Memory { values = new Map<string, unknown>(); get<T>(key: string, fallback?: T): T { return (this.values.has(key) ? this.values.get(key) : fallback) as T; } async update(key: string, value: unknown) { this.values.set(key, value); } }
class Secrets { values = new Map<string, string>(); async store(key: string, value: string) { this.values.set(key, value); } async get(key: string) { return this.values.get(key); } async delete(key: string) { this.values.delete(key); } }
test('AI profiles exclude secrets and preserve key across non-secret update', async () => { const state = new Memory(); const secrets = new Secrets(); const store = new AiProfileStore(state as never, secrets as never); const now = new Date().toISOString(); const profile = { id: 'a', displayName: 'DeepSeek', provider: 'deepseek' as const, baseUrl: 'https://api.deepseek.com', model: 'deepseek-v4-flash', thinkingEnabled: false, timeoutSeconds: 30, maxOutputTokens: 16, createdAt: now, updatedAt: now }; await store.save(profile, 'synthetic-key'); await store.save({ ...profile, displayName: 'Edited' }); assert.equal(await store.key('a'), 'synthetic-key'); assert.equal(JSON.stringify(store.profiles()).includes('synthetic-key'), false); await store.delete('a'); assert.equal(await store.key('a'), undefined); });
test('legacy profile output budget is raised for structured summaries', async () => { const state = new Memory(); const store = new AiProfileStore(state as never, new Secrets() as never); const now = new Date().toISOString(); await store.save({ id: 'legacy', displayName: 'Legacy', provider: 'deepseek', baseUrl: 'https://api.deepseek.com', model: 'm', thinkingEnabled: false, timeoutSeconds: 30, maxOutputTokens: 16, createdAt: now, updatedAt: now }); await store.select('legacy'); assert.equal(store.current()?.maxOutputTokens, minimumStructuredOutputTokens); });
test('provider defaults and public endpoint summaries are safe', () => { assert.equal(defaultsFor('deepseek').model, 'deepseek-v4-flash'); assert.equal(defaultsFor('qwen').model, 'qwen3.7-plus'); assert.equal(qwenRegionOptions.length, 6); assert.equal(qwenWorkspaceBaseUrl('singapore', 'workspace-123'), 'https://workspace-123.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1'); assert.equal(qwenWorkspaceBaseUrl('virginia'), 'https://dashscope-us.aliyuncs.com/compatible-mode/v1'); assert.throws(() => qwenWorkspaceBaseUrl('tokyo'), /Workspace ID/); assert.equal(endpointSummary('https://workspace-123.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1?secret=x'), 'https://<workspace>.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1'); assert.equal(secretKey('id'), 'aiWorklog.aiProvider.id.apiKey'); });
